config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Pages(main) Routes
  root to: 'pages#index', as: 'home'

  
  # get '/projects', to: 'projects#index'
  # get '/projects/new', to: 'projects#new'
  # get '/projects/:id', to: 'projects#show', as: 'projects_show'


  # Projects Routes
  resources :projects
  put '/projects/:id/remove_designer', to: 'projects#remove_designer', as: 'remove_designer'
  post '/projects/:id/message_create_designer', to: 'projects#message_create_designer', as: 'message_create_designer'
  post '/projects/:id/message_create_client', to: 'projects#message_create_client', as: 'message_create_client'

  resources :clients

  resources :designers
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatbox.rb
class Chatbox < ApplicationRecord
  belongs_to :project
  has_many :messages
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :projects
  has_many :messages
end

app/models/designer.rb
class Designer < ApplicationRecord
  belongs_to :user
  has_one :project
  has_many :messages
end

app/models/detail.rb
class Detail < ApplicationRecord
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chatbox
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :designer, optional: true
  has_one_attached :picture
  has_one :chatbox

  enum payment_status: [ "Pending Payment", "Payment Complete" ]
  enum designer_status: [ "Planning", "Awaiting Draft Approval", "Design Complete" ]
  enum client_status: [ "Reviewing Draft", "Reviewing Final Design", "Design Approved" ]
  enum project_status: [ "Draft", "With Designer", "Pending Approval", "Project Complete" ]

  validates :title, :description, :picture, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  has_one :designer
  has_one :client
  has_one :detail
  has_one :address
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    before_action :authenticate_user!, only: [:new]

    def index
    end

    def new
        @client = Client.new
    end

    # Creation of Client & Designer by Association with User Model
    def create
        if current_user.client.nil?
            @client = Client.new(client_params)
            @client.user_id = current_user.id
            @client.save!
        end
        if current_user.designer.nil?
            @designer = Designer.new(designer_params)
            @designer.user_id = current_user.id
            @designer.save!
            redirect_to new_project_path(@client)
        else
            redirect_to new_project_path(@client)
        end
    end

    def edit
    end

    def show

    end

    def update
    end

    def destroy
    end

    private

    def client_params
        params.permit(:user_id)
    end

    def designer_params
        params.permit(:user_id)
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    # Devise
    helper_method :resource_name, :resource, :devise_mapping, :resource_class

    def resource_name
      :user
    end
   
    def resource
      @resource ||= User.new
    end
  
    def resource_class
      User
    end
   
    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end

    # Controller Content
    def index
        @projects = Project.all
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :authenticate_user!, only: [:new]
    before_action :client_authorisation, only: [:create]

    # Project Mechanisms

    def index
        @projects = Project.all
    end

    # Create a new a project as well as initialises a chatbox
    def new
        @project = Project.new
        @project_chatbox = Chatbox.new
    end

    # Upon creation of a project, a chatbox is also created and associated with the client who created the project as well as an association with the project
    def create
        @project = Project.new(project_params)
        @project.client_id = current_user.client.id
        if @project.save!
            @project_chatbox = Chatbox.new
            @project_chatbox.project_id = @project.id
            if @project_chatbox.save!
               redirect_to project_path(@project, @project_chatbox)
            end
        end
    end

    def show
        @project = Project.find params[:id]
    end

    def edit
        @project = Project.find params[:id]
    end

    def update
        @project = Project.find params[:id]

        if @project.designer_id.nil?
            @project.update(designer_id: current_user.designer.id)
            @project.save!
        else
        end

        @project.update(project_status_params.to_h)
        @project.save!
    
        redirect_to project_path(@project)
    end

    def destroy
        @project = Project.find params[:id]
        @project.destroy
        redirect_to home_path
    end

    # ================================================================

    # Designer Mechanisms

    def remove_designer
        @project = Project.find params[:id]
        @project.update(designer_id: nil)
        if @project.save!
            @project_chatbox = Chatbox.find_by(project_id: @project.id)
            @project_chatbox.messages.destroy_all
            if @project_chatbox.save!
                redirect_to project_path(@project)
            end
        end  
    end

    # ================================================================

    # Messaging System

    # Designer Messaging Module
    def message_create_designer
        @project = Project.find params[:id]
        @project_chatbox = @project.chatbox
        @message = Message.create(message_params)
        @message.update(chatbox_id: @project_chatbox.id)
        @message.update(from: @project.designer.user.username)
        @message.update(message_content: params[:message_content])
        if @message.save!
            redirect_to project_path(@project)
        end
    end

    # Client Messaging Module
    def message_create_client
        @project = Project.find params[:id]
        @project_chatbox = @project.chatbox
        @message = Message.create(message_params)
        @message.update(chatbox_id: @project_chatbox.id)
        @message.update(from: @project.client.user.username)
        @message.update(message_content: params[:message_content])
        if @message.save!
            redirect_to project_path(@project)
        end
    end

    # ================================================================

    private



    # Project Authorisation Mechanisms
    def project_params
        params.require(:project).permit(:title, :description, :payment_status, :designer_status, :client_status, :project_status, :picture, :designer_id, :client_id, :authenticity_token) if params[:project]
    end

    def project_status_params
        params.require(:project).permit(:payment_status, :designer_status, :client_status, :project_status, :designer_id) if params[:project]
    end



    # Message Authorisation Mechanisms
    def message_params
        params.require(:message).permit(:project_id, :message_content) if params[:message]
    end



    # Client Authorisation Mechanisms
    def client_params
        params.require(:client).permit(:user_id)
    end

    def client_authorisation
        client = Client.find_by user_id: current_user.id
        if client.nil?
            redirect_to home_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Designated Designer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>  
    <%# Font Awesome %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-vp86vTRFVJgpjF9jiIGPEEqYqlDwgyBgEF109VFjmqGmIY/Y4HV4d3Gp2irVfcrp" crossorigin="anonymous">

    <%# Google Fonts%>
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@200;300;600&display=swap" rel="stylesheet">
  </head>

  <body>
  <div class="noticeAndAlertContainer">
      <p class="notice"><%= notice %></p>
  </div>
  <div class="noticeAndAlertContainer">
      <p class="alert"><%= alert %></p>
  </div>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<section class="indexMainSection">
    <section class="frontCoverSection">
        <section class="navBarSection">
        <div class="navBarLogoTitleSection">
            <i class="fas fa-magic designatedDesignerLogo"></i>
            <h1 class="designatedDesignerTitle">Designated Designer</h1>
        </div>
        <% if user_signed_in? %>
        <div>
            <p class="frontCoverUserDetails">Logged in as: <%= current_user.username %> | Account ID: <%= current_user.id %></p>
        </div>
        <% end %>
            <div class="navBarLinksSection">
                <% if user_signed_in? %>
                    <%= link_to "New Job", '/clients', method: 'post', class: "navLinkButtons" %>
                    <%= link_to 'View Jobs', designers_path, method: 'post', class: "navLinkButtons" %>
                    <%= link_to "Logout", destroy_user_session_path, method: "delete", class: "navLinkButtons" %>
                <% else %>
                    <div class="navBarRegistrationLinkContainer">
                        <%= link_to "Register", new_user_registration_path, class: "navLinkButtons" %>
                    </div>
                <% end %>
        </div>
        </section>
        <% if user_signed_in? %>
        <section class="frontCoverUserControls">
                <div>
                    <%= button_to "New Job", '/clients', method: 'post', class: "userControls" %>
                </div>
                <div>
                    <%= button_to 'View Jobs', designers_path, method: 'post', class: "userControls" %>
                </div>
        </section>
        <% else %>
        <section class="frontCoverFormSection">
            <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
                <div class="formInputFieldContainer">
                <%= f.email_field :email, autofocus: true, autocomplete: "email", placeholder: "Your Email Here", class: "formInputField" %>
                </div>
                <div class="formInputFieldContainer">
                <%= f.password_field :password, autocomplete: "current-password", placeholder: "Your Password Here", class: "formInputField" %>
                </div>
                <div class="formInputFieldRememberContainer">
                    <% if devise_mapping.rememberable? %>
                        <div class="coverFormCheckboxSection">
                            <%= f.check_box :remember_me, class: "rememberMeCheckbox"%>
                            <%= f.label :remember_me, class: "rememberMeLabel" %>
                        </div>    
                    <% end %>
                    <div class="coverFormLoginButtonSection">
                        <%= f.submit "Log in", class: "coverFormLoginButton" %>
                    </div>
                </div>
            <% end %>
        </section>
        <% end %>
    </section>
</section>
<% if user_signed_in? %>
    <section class="aboutDesignatedDesignerSection">
    </section>
<% else %>
    <section class="aboutDesignatedDesignerSection">
        <section class="aboutDesignatedDesignerContainer">
            <h1 class="aboutDesignatedDesignerContainerTitle">Welcome to Designated Designer</h1>
            <p class="aboutDesignatedDesignerContainerText">There is a huge problem in the design industry where the working environment of most designers fall into a toxic category. This is due to marketing and design being a sub-category of a company that doesn't generate revenue or lack of understanding by employers on the importance of good design and the value towards a brand a good designer can offer. It is well known that design is an extremely challenging profession that requires patience and strong contextual as well as conceptual thinking. The core value a designer can bring is towards branding and identity, where a designer can visually generate a company's persona, allowing both external and internal stakeholders to identify with a company on an interpersonal level. This is the power a designer can offer, however in the industry it is often over-looked and misunderstood.</p>
            <p class="aboutDesignatedDesignerContainerText">This market place will be implemented as "designer focused" and help designers to focus on their passion of design with more "design" wins as completed projects. Projects will be delivered through an interactive portal where designers can choose what project they want to work on and chat in real time with the client via a built-in messaging interface. No physical interaction or contact will be required to get the job done as the client and designer both have to work together to get the final design approved. This level of collaboration is something missing as professional designers are often left with obscure briefs to do everything themselves and return a semi polished draft for review. Often, designers are left to chase up clients to review work for a project they have created. Through this two-way marketplace as a service, projects don't move forward unless the other party does their part.</p>
        </section>
    </section>
<% end %>
<footer class="indexMainFooter">
    <img src="aBuiDev_grey.svg" width="50px;">
    <p class="indexMainFooterText">Created by aBuiDev | 2020</p>
</footer>

app/views/shared/_navbar.html.erb
<section class="globalNavBarSection">
    <section class="navBarSection">
       <div class="navBarLogoTitleSection">
          <i class="fas fa-magic designatedDesignerLogo"></i>
          <h1 class="designatedDesignerTitle">Designated Designer</h1>
       </div>
       <% if user_signed_in? %>
            <div>
                <p class="frontCoverUserDetails">Logged in as: <%= current_user.username %> | Account ID: <%= current_user.id %></p>
            </div>
       <% end %>
            <div class="navBarLinksSection">
                <% if user_signed_in? %>
                    <%= link_to "New Job", '/clients', method: 'post', class: "navLinkButtons" %>
                    <%= link_to 'View Jobs', designers_path, method: 'post', class: "navLinkButtons" %>
                    <%= link_to "Logout", destroy_user_session_path, method: "delete", class: "navLinkButtons" %>
                <% else %>
                    <%= link_to "back", home_path, class: "navLinkButtons" %>
                <% end %>
        </div>
    </section>
</section>

app/views/shared/_project_statuses.html.erb
<div class="projectStatusInterfaceContainer">
    <p class="projectStatusInterfaceTitle">Project Status Interface:</p>
</div>

<section class="projectStatusesSection">
    <div class="projectStatusesContainer">
        <div class="projectStatusElementContainer">
            <p class="statusTitle">Payment Status:</p>
            <p class="statusOutput"><%= @project[:payment_status] %></p>
        </div>
        <div class="projectStatusElementContainer">
            <p class="statusTitle">Designer Status:</p>
            <p class="designerStatusOutput"><%= @project[:designer_status] %></p>
        </div>
        <div class="projectStatusElementContainer">
            <p class="statusTitle">Client Status:</p>
            <p class="statusOutput"><%= @project[:client_status] %></p>
        </div>
        <div class="projectStatusElementContainer">
            <p class="statusTitle">Project Status:</p>
            <p class="statusOutput"><%= @project[:project_status] %></p>
        </div>
    </div>
</section>