config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # Pages(main) Routes
  root to: 'pages#index', as: 'home'

  
  # get '/projects', to: 'projects#index'
  # get '/projects/new', to: 'projects#new'
  # get '/projects/:id', to: 'projects#show', as: 'projects_show'


  # Projects Routes
  resources :projects
  put '/projects/:id/remove_designer', to: 'projects#remove_designer', as: 'remove_designer'
  post '/projects/:id/message_create_designer', to: 'projects#message_create_designer', as: 'message_create_designer'
  post '/projects/:id/message_create_client', to: 'projects#message_create_client', as: 'message_create_client'

  resources :clients

  resources :designers
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :client
  belongs_to :designer, optional: true
  has_one_attached :picture
  has_one :chatbox

  enum payment_status: [ "Pending Payment", "Payment Complete" ]
  enum designer_status: [ "Planning", "Awaiting Draft Approval", "Design Complete" ]
  enum client_status: [ "Reviewing Draft", "Reviewing Final Design", "Design Approved" ]
  enum project_status: [ "Draft", "With Designer", "Pending Approval", "Project Complete" ]

  validates :title, :description, :picture, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

    before_action :authenticate_user!, only: [:new]
    before_action :client_authorisation, only: [:create]

    # Project Mechanisms

    def index
        @projects = Project.all
    end

    # Create a new a project as well as initialises a chatbox
    def new
        @project = Project.new
        @project_chatbox = Chatbox.new
    end

    # Upon creation of a project, a chatbox is also created and associated with the client who created the project as well as an association with the project
    def create
        @project = Project.new(project_params)
        @project.client_id = current_user.client.id
        if @project.save!
            @project_chatbox = Chatbox.new
            @project_chatbox.project_id = @project.id
            if @project_chatbox.save!
               redirect_to project_path(@project, @project_chatbox)
            end
        end
    end

    def show
        @project = Project.find params[:id]
    end

    def edit
        @project = Project.find params[:id]
    end

    def update
        @project = Project.find params[:id]

        if @project.designer_id.nil?
            @project.update(designer_id: current_user.designer.id)
            @project.save!
        else
        end

        @project.update(project_status_params.to_h)
        @project.save!
    
        redirect_to project_path(@project)
    end

    def destroy
        @project = Project.find params[:id]
        @project.destroy
        redirect_to home_path
    end

    # ================================================================

    # Designer Mechanisms

    def remove_designer
        @project = Project.find params[:id]
        @project.update(designer_id: nil)
        if @project.save!
            @project_chatbox = Chatbox.find_by(project_id: @project.id)
            @project_chatbox.messages.destroy_all
            if @project_chatbox.save!
                redirect_to project_path(@project)
            end
        end  
    end

    # ================================================================

    # Messaging System

    # Designer Messaging Module
    def message_create_designer
        @project = Project.find params[:id]
        @project_chatbox = @project.chatbox
        @message = Message.create(message_params)
        @message.update(chatbox_id: @project_chatbox.id)
        @message.update(from: @project.designer.user.username)
        @message.update(message_content: params[:message_content])
        if @message.save!
            redirect_to project_path(@project)
        end
    end

    # Client Messaging Module
    def message_create_client
        @project = Project.find params[:id]
        @project_chatbox = @project.chatbox
        @message = Message.create(message_params)
        @message.update(chatbox_id: @project_chatbox.id)
        @message.update(from: @project.client.user.username)
        @message.update(message_content: params[:message_content])
        if @message.save!
            redirect_to project_path(@project)
        end
    end

    # ================================================================

    private



    # Project Authorisation Mechanisms
    def project_params
        params.require(:project).permit(:title, :description, :payment_status, :designer_status, :client_status, :project_status, :picture, :designer_id, :client_id, :authenticity_token) if params[:project]
    end

    def project_status_params
        params.require(:project).permit(:payment_status, :designer_status, :client_status, :project_status, :designer_id) if params[:project]
    end



    # Message Authorisation Mechanisms
    def message_params
        params.require(:message).permit(:project_id, :message_content) if params[:message]
    end



    # Client Authorisation Mechanisms
    def client_params
        params.require(:client).permit(:user_id)
    end

    def client_authorisation
        client = Client.find_by user_id: current_user.id
        if client.nil?
            redirect_to home_path
        end
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/index.html.erb
<%= render "shared/navbar"%>

<section class="projectsContainer">
    <% @projects.each do | project | %>

        <div class="projectCard">
            <div class="projectCardImage" style="background-image: url(<%= rails_blob_path(project.picture, disposition: "attachment", only_path: true) %>); background-position: center; background-repeat: no-repeat; background-size: cover;"></div>
            <div class="projectCardInfoContainer">
                <div class="projectCardTitle">
                    <%= project[:title ]%>
                </div>
                <div class="projectCardClient">
                    <p class="projectCardClientTitle">Client:</p>
                    <p class="projectCardClientUsername"><%= project.client.user.username %></p>
                </div>
                <div class="projectCardButton">
                    <%= link_to 'View Project', project, style: "text-decoration: none; color: black" %>
                </div>
            </div>
        </div>
    
    <% end %>
</section>

app/views/projects/new.html.erb
<section class="frontCoverSection">
    <section class="navBarSection">
       <div class="navBarLogoTitleSection">
          <i class="fas fa-magic designatedDesignerLogo"></i>
          <h1 class="designatedDesignerTitle">Designated Designer</h1>
       </div>
       <% if user_signed_in? %>
       <div>
           <p class="frontCoverUserDetails">Logged in as: <%= current_user.username %> | Account ID: <%= current_user.id %></p>
       </div>
       <% end %>
        <div class="navBarLinksSection">
              <% if user_signed_in? %>
                  <%= link_to "New Job", '/clients', method: 'post', class: "navLinkButtons" %>
                  <%= link_to 'View Jobs', designers_path, method: 'post', class: "navLinkButtons" %>
                  <%= link_to "Logout", destroy_user_session_path, method: "delete", class: "navLinkButtons" %>
              <% else %>
                  <%= link_to "back", home_path, class: "navLinkButtons" %>
              <% end %>
       </div>
    </section>
        <section class="userRegistrationFormSection">
            <%= form_with model: @project, local: true do | form | %>
                <div class="userRegistrationFieldContainer">
                    <%= form.text_field :title, placeholder: "Name of Project Here", class: "userRegistrationInputField" %>
                </div>
                <div class="userRegistrationFieldContainer">
                    <%= form.text_field :description, placeholder: "Enter Project Description Here", class: "userRegistrationInputField" %>
                </div>
                <div class="newProjectUploadImageContainer">
                    <%= form.file_field :picture, accept: 'image/png, image/jpg, image/jpeg' %>
                    <%= form.submit "Save", class: "uploadImageButton" %>
                </div>
            <% end %>
        </section>
    </section>
</section>

<section class="homePageBodySeparatorOne">

</section>

<footer class="indexMainFooter">
    <img src="../aBuiDev_grey.svg" width="50px;">
    <p class="indexMainFooterText">Created by aBuiDev | 2020</p>
</footer>

app/views/projects/show.html.erb
<%= render "shared/navbar" %>

<section class="projectInformationContainer">
    <h1 class="projectTitle"><%= @project[:title] %><h1>
    <div class="projectInformationElementSection">
        <p class="projectInformationElement">Project Created By: <%= @project.client.user[:username] %></p>
        <p class="projectInformationElement">|</p>
        <p class="projectInformationElement">Project ID: <%= @project.id %></p>
    </div>
</section>

<%# Project Viewport Section %>
<section class="projectImageViewportSection">
        <section class="projectImageViewport" style="background-image: url(<%= rails_blob_path(@project.picture, disposition: "attachment", only_path: true) %>); background-position: center; background-repeat: no-repeat; background-size: cover;">
    </section>
    <%# Join, Remove Designer or Quit Project Button %>
    <section class="projectButtonSection">
        <% if @project.designer_id.nil? && @project.client.id != current_user.client.id %>
            <%= form_with model: @project, local: true do | form | %>
                <%= form.submit "Join Project", class: "projectButtonJoin" %>
            <% end %>
        <% else %>
            <% if @project.designer_id == current_user.designer.id || @project.client.id == current_user.client.id %>
                <% if @project.designer_id == current_user.designer.id %>
                    <%= link_to 'Quit Project', remove_designer_path, method: 'put', class: "projectButtonQuit" %>
                <% else %>
                    <% if @project.designer_id.nil? %>
                        <p style="display: none"></p>
                    <% else %>
                        <%= link_to 'Drop Designer', remove_designer_path, method: 'put', class: "projectButtonQuit" %>
                    <% end %>
                <% end %>
            <% else %>
                <p style="display: none"></p>
            <% end %>
        <% end %>
    </section>
</section>

<%# Project Design Brief Section %>
<section class="projectBriefSection">
    <p class="projectBriefSectionTitle">Project Design Brief</p>
    <div class="projectBriefSectionContentContainer">
        <p class="projectBriefContent"><%= @project[:description] %></p>
    </div>
</section>





<%# HUD Interface %>


<% if @project.designer_id == current_user.designer.id && @project.client.id != current_user.client.id %>
<section class="hudSection">
    <section class="InterfaceSection">
        <div class="projectStatusInterfaceOwnerContainer">
            <p class="projectStatusInterfaceDesignerTile"><%= @project.designer.user.username %>'s' Designer HUD<p>
        </div>
        
        <%# Project Statuses Output %>
        <%= render "shared/project_statuses" %>

        <%# Designer Controls %>
        <section class="projectStatusesControllersSection">
            <div class="projectStatusesControllerTitleContainer">
                <h1 class="interfaceHeadings">Designer Controls:</h1>
            </div>
            <div class="projectStatusesControllerContainer">
                <%= form_with model: @project, local: true do | form | %>
                    <div class="projectStatusDropDownSelectorElement">
                        <div class="projectStatusDropDown">
                            <%= form.select :designer_status, [ "Planning", "Awaiting Draft Approval", "Design Complete" ], placeholder: "Select Status from Dropdown" %>
                        </div>
                        <div>
                            <%= form.submit "Update", class: "projectStatusesSubmitButton" %>
                        </div>
                    </div>
                <% end %>  
            </div>
        </section> 
    </section>
</section>

<% elsif @project.client_id == current_user.client.id %>
<section class="hudSection">
    <section class="interfaceSection">
        <div class="projectStatusInterfaceOwnerContainer">
            <p class="projectStatusInterfaceDesignerTile"><%= @project.client.user.username %>'s' Client HUD<p>
        </div>

        <%# Project Statuses Output %>
        <%= render "shared/project_statuses" %>

        <%# Project Statuses Controller %>
        <section class="projectStatusesControllersSection">
            <div class="projectStatusesControllerTitleContainer">
                <h1 class="interfaceHeadings">Client Controls:</h1>
            </div>
            <div class="projectStatusesControllerContainer">
                <%= form_with model: @project, local: true do | form | %>
                    <div class="projectStatusDropDownSelectorElement">
                        <div class="projectStatusDropDown">
                            <%= form.select :payment_status, [ "Pending Payment", "Payment Complete" ] %>
                        </div>
                        <div>
                            <%= form.submit "Update", class: "projectStatusesSubmitButton" %>
                        </div>
                    </div>
                <% end %>  
                <%= form_with model: @project, local: true do | form | %>
                    <div class="projectStatusDropDownSelectorElement">
                        <div class="projectStatusDropDown">
                            <%= form.select :client_status, [ "Reviewing Draft", "Reviewing Final Design", "Design Approved" ] %>
                        </div>
                        <div>
                            <%= form.submit "Update", class: "projectStatusesSubmitButton" %>
                        </div>
                    </div>
                <% end %>
                <%= form_with model: @project, local: true do | form | %>
                    <div class="projectStatusDropDownSelectorElement">
                        <div class="projectStatusDropDown">
                            <%= form.select :project_status, [ "Draft", "With Designer", "Pending Approval", "Project Complete" ] %>
                        </div>
                        <div>
                            <%= form.submit "Update", class: "projectStatusesSubmitButton" %>
                        </div>
                    </div>
                <% end %>
            </div>
        </section>
    </section>
</section>
<% elsif @project.designer_id == @project.client_id %>
    <p style="display: none"></p>
<% elsif @project.designer_id.nil? %>
    <p style="display: none"></p>
<% elsif @project.client_id.nil? %>
    <p style="display: none"></p>
<% end %>


<% if @project.designer_id == current_user.designer.id && @project.client.id != current_user.client.id %>
<%# Client Chat Mechanism %>
<section class="chatInterfaceSection">
    <section class="chatInterfaceContainer">
        <div class="chatInterfaceTitleContainer">
            <h1 class="chatInterfaceHeading">Chat Interface:</h1>
        </div>
        <% @project.chatbox.messages.each do | message | %>
            <div class="clientMessageContainer">
                <p class="messageSentBy"><%= message[:from] %>:</p>
                <p class="messageBox"><%= message[:message_content] %></p>
            </div>
        <% end %>

        <%= form_with url: message_create_designer_path, local: true do | form | %>
            <section class="messageInputSection">
                <div class="messageInputContainer">
                    <div class="messageInputElement">
                        <%= form.text_area :message_content, placeholder: "Type your message here...", class: "messageInputTextArea"  %>
                    </div>
                    <%= form.submit "Send", class: "messageSubmitButton" %>
                </div>
            </section>
        <% end %>
    </section>
</section>
<% elsif @project.client_id == current_user.client.id %>
<%# Designer Chat Mechanism %>
<section class="chatInterfaceSection">
    <section class="chatInterfaceContainer">
        <div class="chatInterfaceTitleContainer">
            <h1 class="chatInterfaceHeading">Chat Interface:</h1>
        </div>
        <% @project.chatbox.messages.each do | message | %>
            <div class="designerMessageContainer">
                <p class="messageSentBy"><%= message[:from] %>:</p>
                <p class="messageBox"><%= message[:message_content] %></p>
            </div>
        <% end %>

        <%= form_with url: message_create_client_path, local: true do | form | %>
            <section class="messageInputSection">
                <div class="messageInputContainer">
                    <div class="messageInputElement">
                        <%= form.text_area :message_content, placeholder: "Type your message here...", class: "messageInputTextArea"  %>
                    </div>
                    <%= form.submit "Send", class: "messageSubmitButton" %>
                </div>
            </section>
        <% end %>
    </section>
</section>
<% elsif @project.designer_id == @project.client_id %>
    <p style="display: none"></p>
<% elsif @project.designer_id.nil? %>
    <p style="display: none"></p>
<% elsif @project.client_id.nil? %>
    <p style="display: none"></p>
<% end %>